---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ print (include "electrs.fullname" .) "-electrs" | quote }}
  {{- with (merge .Values.global.labels .Values.configMap.labels (include "electrs.labels" . | fromYaml)) }}
  labels:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  {{- with (merge .Values.global.annotations .Values.configMap.annotations) }}
  annotations:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
data:
  config.toml: |
    {{- range $k, $v := .Values.electrs.config }}
    {{ $k }} = {{ tpl $v $ | quote }}
    {{- end }}
