---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ print (include "bitcoin-core.fullname" .) "-bitcoind" | quote }}
  {{- with (merge .Values.global.labels .Values.configMap.labels (include "bitcoin-core.labels" . | fromYaml)) }}
  labels:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  {{- with (merge .Values.global.annotations .Values.configMap.annotations) }}
  annotations:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
data:
  bitcoin.conf: |
    printtoconsole=1
    server=1
    {{- range $k, $v := .Values.bitcoind.config }}
    {{ $k }}={{ tpl $v $ }}
    {{- end }}
