---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ print (include "bitcoin-core.name" .) "-entrypoint" | quote }}
  labels: {{- include "bitcoin-core.labels" . | nindent 4 }}
data:
  entrypoint: |-
    #!/bin/ash
    set -ex
    exec su-exec bitcoin bitcoind -datadir="$BITCOIN_DATA"
