{{- if and .Values.exporter.enabled .Values.podMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor") }}
---
apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: {{ include "bitcoin-core.fullname" . | quote }}
  {{- with (merge .Values.global.labels .Values.pod.labels (include "bitcoin-core.labels" . | fromYaml)) }}
  labels:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  {{- with (merge .Values.global.annotations .Values.pod.annotations) }}
  annotations:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels: {{- include "bitcoin-core.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: "exporter"
      path: "/metrics"
      interval: {{ .Values.podMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.podMonitor.timeout | quote }}
{{- end }}
