{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ print (include "bitcoin-core.name" .) "-data" | quote }}
  labels: {{- include "bitcoin-core.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  {{- if eq "-" . }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
