---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "bitcoin-core.name" . | quote }}
  labels: {{- include "bitcoin-core.labels" . | nindent 4 }}
spec:
  selector: {{- include "bitcoin-core.selectorLabels" . | nindent 4 }}
  type: {{ .Values.bitcoind.rpc.service }}
  ports:
    - name: "rpc"
      port: {{ .Values.bitcoind.rpc.port }}
      targetPort: "rpc"
      protocol: "TCP"
    {{- if .Values.exporter.enabled }}
    - name: "exporter"
      port: 9332
      targetPort: "exporter"
      protocol: "TCP"
    {{- end }}
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ print (include "bitcoin-core.name" .) "-p2p" | quote }}
  labels: {{- include "bitcoin-core.labels" . | nindent 4 }}
spec:
  selector: {{- include "bitcoin-core.selectorLabels" . | nindent 4 }}
  type: {{ .Values.bitcoind.p2p.service }}
  ports:
    - name: "p2p"
      port: {{ .Values.bitcoind.p2p.port }}
      targetPort: "p2p"
      protocol: "TCP"

