---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ print (include "bitcoin-core.fullname" .) | quote }}
  {{- with (merge .Values.global.labels .Values.service.labels (include "bitcoin-core.labels" . | fromYaml)) }}
  labels:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  {{- with (merge .Values.global.annotations .Values.service.annotations) }}
  annotations:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  selector: {{- include "bitcoin-core.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | quote }}
  ports:
    {{- if .Values.service.enableP2p }}
    - name: "p2p"
      port: {{ .Values.bitcoind.ports.p2p }}
      targetPort: "p2p"
    {{- end }}
    {{- if .Values.service.enableRpc }}
    - name: "rpc"
      port: {{ .Values.bitcoind.ports.rpc }}
      targetPort: "rpc"
    {{- end }}
