---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ include "bitcoin-core.name" . | quote }}
  labels: {{- include "bitcoin-core.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "bitcoin-core.name" . | quote }}
  selector:
    matchLabels: {{- include "bitcoin-core.selectorLabels" . | nindent 6 }}
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      name: {{ include "bitcoin-core.fullname" . | quote }}
      labels: {{- include "bitcoin-core.labels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.exporter.enabled }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.exporter.enabled }}
        prometheus.io/port: "9332"
        prometheus.io/scrape: "true"
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "bitcoin-core"
          {{- with .Values.bitcoind.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ print .Values.bitcoind.image.repository ":" (.Values.bitcoind.image.tag | default .Chart.AppVersion) | quote }}
          imagePullPolicy: {{ .Values.bitcoind.image.pullPolicy | quote }}
          {{- with .Values.bitcoind.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "data"
              mountPath: "/home/bitcoin/.bitcoin"
            - name: "config"
              mountPath: "/home/bitcoin/.bitcoin/bitcoin.conf"
              subPath: "bitcoin.conf"
            - name: "entrypoint"
              mountPath: "/entrypoint.sh"
              subPath: "entrypoint"
          ports:
            - name: "rpc"
              containerPort: {{ .Values.bitcoind.rpc.port }}
            - name: "p2p"
              containerPort: {{ .Values.bitcoind.p2p.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.bitcoind.rpc.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.bitcoind.rpc.port }}
            initialDelaySeconds: 5
            periodSeconds: 30
        {{- if .Values.exporter.enabled }}
        - name: "bitcoin-core-exporter"
          {{- with .Values.exporter.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ print .Values.exporter.image.repository ":" .Values.exporter.image.tag | quote }}
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy | quote }}
          {{- with .Values.exporter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "config"
              mountPath: "/home/bitcoin/.bitcoin/bitcoin.conf"
              subPath: "bitcoin.conf"
          env:
            - name: "REFRESH_SECONDS"
              value: "1"
            - name: "LOG_LEVEL"
              value: "INFO"
            - name: "BITCOIN_RPC_HOST"
              value: "bitcoin-core"
            - name: "BITCOIN_CONF_PATH"
              value: "/home/bitcoin/.bitcoin/bitcoin.conf"
          ports:
            - name: "exporter"
              containerPort: 9332
          readinessProbe:
            tcpSocket:
              port: 9332
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9332
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
        {{- end }}
      volumes:
        - name: "entrypoint"
          configMap:
            name: {{ print (include "bitcoin-core.name" .) "-entrypoint" | quote }}
            defaultMode: 0777
        - name: "config"
          configMap:
            name: {{ print (include "bitcoin-core.name" .) "-bitcoind" | quote }}
        {{- if not .Values.persistence.enabled }}
        - name: "data"
          emptyDir: {}
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: "data"
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
