---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ include "bitcoin-core.fullname" . | quote }}
  {{- with (merge .Values.global.labels .Values.controller.labels (include "bitcoin-core.labels" . | fromYaml)) }}
  labels:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  {{- with (merge .Values.global.annotations .Values.controller.annotations) }}
  annotations:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  serviceName: {{ include "bitcoin-core.name" . | quote }}
  selector:
    matchLabels: {{- include "bitcoin-core.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  template:
    metadata:
      name: {{ include "bitcoin-core.fullname" . | quote }}
      {{- with (merge .Values.global.labels .Values.pod.labels (include "bitcoin-core.labels" . | fromYaml)) }}
      labels:
        {{- range $k, $v := . }}
        {{- $v = tpl $v $ }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
      {{- with (merge .Values.global.annotations .Values.pod.annotations (include "bitcoin-core.prometheusAnnotations" . | fromYaml)) }}
      annotations:
        {{- range $k, $v := . }}
        {{- $v = tpl $v $ }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "bitcoin-core"
          {{- with .Values.bitcoind.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ print .Values.bitcoind.image.repository ":" (.Values.bitcoind.image.tag | default .Chart.AppVersion) | quote }}
          imagePullPolicy: {{ .Values.bitcoind.image.pullPolicy | quote }}
          {{- with .Values.bitcoind.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "config"
              mountPath: "/home/bitcoin/.bitcoin/bitcoin.conf"
              subPath: "bitcoin.conf"
            - name: "data"
              mountPath: "/home/bitcoin/.bitcoin"
            - name: "entrypoint"
              mountPath: "/entrypoint.sh"
              subPath: "entrypoint"
          ports:
            - name: "rpc"
              containerPort: {{ .Values.bitcoind.ports.rpc }}
            - name: "p2p"
              containerPort: {{ .Values.bitcoind.ports.p2p }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.bitcoind.ports.rpc }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.bitcoind.ports.rpc }}
            initialDelaySeconds: 5
            periodSeconds: 30
        {{- if .Values.exporter.enabled }}
        - name: "bitcoin-core-exporter"
          {{- with .Values.exporter.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ print .Values.exporter.image.repository ":" .Values.exporter.image.tag | quote }}
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy | quote }}
          {{- with .Values.exporter.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "config"
              mountPath: "/home/bitcoin/.bitcoin/bitcoin.conf"
              subPath: "bitcoin.conf"
            - name: "data"
              mountPath: "/home/bitcoin/.bitcoin"
              readOnly: true
          env:
            - name: "REFRESH_SECONDS"
              value: "1"
            - name: "LOG_LEVEL"
              value: "WARN"
            - name: "BITCOIN_RPC_HOST"
              value: {{ include "bitcoin-core.name" . | quote }}
            - name: "BITCOIN_CONF_PATH"
              value: "/home/bitcoin/.bitcoin/bitcoin.conf"
          ports:
            - name: "exporter"
              containerPort: 9332
          readinessProbe:
            tcpSocket:
              port: 9332
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9332
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
        {{- end }}
      volumes:
        - name: "config"
          configMap:
            name: {{ print (include "bitcoin-core.fullname" .) "-bitcoind" | quote }}
        {{- if not .Values.persistence.enabled }}
        - name: "data"
          emptyDir: {}
        {{- else if .Values.persistence.existingClaim }}
        - name: "data"
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
        - name: "entrypoint"
          configMap:
            name: {{ print (include "bitcoin-core.fullname" .) "-entrypoint" | quote }}
            defaultMode: 0777
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    -
      metadata:
        name: "data"
        {{- with (merge .Values.global.labels .Values.persistence.labels (include "bitcoin-core.labels" . | fromYaml)) }}
        labels:
          {{- range $k, $v := . }}
          {{- $v = tpl $v $ }}
          {{ $k }}: {{ $v | quote }}
          {{- end }}
        {{- end }}
        {{- with (merge .Values.global.annotations .Values.persistence.annotations) }}
        annotations:
          {{- range $k, $v := . }}
          {{- $v = tpl $v $ }}
          {{ $k }}: {{ $v | quote }}
          {{- end }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
  {{- end }}
